export const APIID = {
    USER_GET: "api.user.get",
    USER_CREATE: "api.user.create",
    USER_UPDATE: "api.user.update",
    USER_LIST: "api.user.list",
    USER_RESET_PASSWORD: "api.user.resetPassword",
    USER_DELETE: "api.user.delete",
    ROLE_GET: "api.role.get",
    ROLE_CREATE: "api.role.create",
    ROLE_UPDATE: "api.role.update",
    ROLE_SEARCH: "api.role.search",
    ROLE_DELETE: "api.role.delete",
    PRIVILEGE_BYROLEID: "api.privilegebyRoleId.get",
    PRIVILEGE_BYPRIVILEGEID: 'api.privilegebyPrivilegeId.get',
    PRIVILEGE_CREATE: 'api.privilege.create',
    PRIVILEGE_DELETE: 'api.privilege.delete',
    COHORT_MEMBER_GET: "api.cohortmember.get",
    COHORT_MEMBER_CREATE: "api.cohortmember.create",
    COHORT_MEMBER_UPDATE: "api.cohortmember.update",
    COHORT_MEMBER_SEARCH: "api.cohortmember.list",
    COHORT_MEMBER_DELETE: "api.cohortmember.delete",
}
