export const APIID = {
    USER_GET: "api.user.get",
    USER_CREATE: "api.user.create",
    USER_UPDATE: "api.user.update",
    USER_LIST: "api.user.list",
    USER_RESET_PASSWORD: "api.user.resetPassword",
    USER_DELETE: "api.user.delete",
    ROLE_GET: "api.role.get",
    ROLE_CREATE: "api.role.create",
    ROLE_UPDATE: "api.role.update",
    ROLE_SEARCH: "api.role.search",
    ROLE_DELETE: "api.role.delete",
    PRIVILEGE_BYROLEID: "api.privilegebyRoleId.get",
    PRIVILEGE_BYPRIVILEGEID: 'api.privilegebyPrivilegeId.get',
    PRIVILEGE_CREATE: 'api.privilege.create',
    PRIVILEGE_DELETE: 'api.privilege.delete',
    USERROLE_CREATE: "api.userRole.create",
    USERROLE_GET: "api.userRole.get",
    USERROLE_DELETE: "api.userRole.delete",
    COHORT_CREATE: "api.cohort.create",
    COHORT_LIST: "api.cohort.list",
    COHORT_READ: "api.cohort.read",
    COHORT_UPDATE: "api.cohort.update",
    COHORT_DELETE: "api.cohort.delete",
    FIELDVALUES_CREATE: "api.fieldValues.create"
}
