#It is deploying on server 15.206.144.84 For Dev Environment only please note. 
name: Deploy to  Tekdi-ou-shiskha-backend
on: 
  push:  
    branches:
      - altv1
jobs: 
  build:
    name: Generate Build and Deploy to DEV
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Setup Node Env
        uses: actions/setup-node@v3
        with:
          node-version: 21.1.0
          
      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY_ALT_DEV_TEKDI_OU }}
          REMOTE_HOST: ${{ secrets.HOST_DNS_ALT_DEV_TEKDI_OU }}
          REMOTE_USER: ${{ secrets.USERNAME_ALT_DEV_TEKDI_OU }}
       

      - name: Set up SSH key
        run: |
         mkdir -p ~/.ssh
         echo "${{ secrets.EC2_SSH_KEY_ALT_DEV_TEKDI_OU }}" > ~/.ssh/id_rsa
         chmod 600 ~/.ssh/id_rsa
         # Add the SSH key to the known_hosts file (replace hostname with your actual hostname)
         ssh-keyscan -H ${{ secrets.HOST_DNS_ALT_DEV_TEKDI_OU }} >> ~/.ssh/known_hosts
         sudo apt-get install sshpass

      - name: Deploy to server
        run: |
          sshpass -p '${{ secrets.EC2_SSH_KEY_ALT_DEV_TEKDI_OU }}' ssh -v -o StrictHostKeyChecking=no ${{ secrets.USERNAME_ALT_DEV_TEKDI_OU }}@${{ secrets.HOST_DNS_ALT_DEV_TEKDI_OU }} <<'ENDSSH'
          cd /home/ubuntu/shiksha-backend
          ./deploy.sh
          ENDSSH
